const courses = [
  {
    title: 'HTML',
    description: 'Learn the foundation of web development with HTML5 semantic elements, forms, and accessibility.',
    icon: 'FileCode',
    orderNumber: 1,
    color: '#e34f26',
    lessons: [
      { title: 'Introduction to HTML', description: 'Understanding HTML documents, doctypes, and basic structure', estimatedTime: 30, orderNumber: 1, resources: { documentation: 'https://developer.mozilla.org/en-US/docs/Web/HTML', youtube: 'https://www.youtube.com/watch?v=qz0aGYrrlhU' } },
      { title: 'HTML Elements & Tags', description: 'Common HTML elements: headings, paragraphs, lists, links, images', estimatedTime: 45, orderNumber: 2 },
      { title: 'HTML Forms', description: 'Input types, form validation, labels, fieldsets', estimatedTime: 60, orderNumber: 3 },
      { title: 'Semantic HTML5', description: 'Using semantic tags: header, nav, main, article, section, footer', estimatedTime: 30, orderNumber: 4 },
      { title: 'HTML Tables & Media', description: 'Tables, audio, video, and embedding content', estimatedTime: 45, orderNumber: 5 },
      { title: 'HTML Accessibility', description: 'ARIA attributes, screen readers, and accessibility best practices', estimatedTime: 45, orderNumber: 6 },
    ],
  },
  {
    title: 'CSS',
    description: 'Master styling with CSS3, Flexbox, Grid, animations, and responsive design.',
    icon: 'Palette',
    orderNumber: 2,
    color: '#264de4',
    lessons: [
      { title: 'CSS Fundamentals', description: 'Selectors, properties, values, and the cascade', estimatedTime: 45, orderNumber: 1 },
      { title: 'Box Model & Layout', description: 'Margin, padding, border, and display properties', estimatedTime: 45, orderNumber: 2 },
      { title: 'Flexbox', description: 'Flexible box layout for one-dimensional layouts', estimatedTime: 60, orderNumber: 3 },
      { title: 'CSS Grid', description: 'Two-dimensional grid layout system', estimatedTime: 60, orderNumber: 4 },
      { title: 'Responsive Design', description: 'Media queries, mobile-first approach, and fluid layouts', estimatedTime: 45, orderNumber: 5 },
      { title: 'CSS Animations', description: 'Transitions, keyframe animations, and transforms', estimatedTime: 45, orderNumber: 6 },
      { title: 'CSS Variables & Modern CSS', description: 'Custom properties, calc(), clamp(), and modern features', estimatedTime: 30, orderNumber: 7 },
    ],
  },
  {
    title: 'JavaScript',
    description: 'Deep dive into JavaScript fundamentals, ES6+, async programming, and DOM manipulation.',
    icon: 'Braces',
    orderNumber: 3,
    color: '#f7df1e',
    lessons: [
      { title: 'JS Fundamentals', description: 'Variables, data types, operators, and control flow', estimatedTime: 60, orderNumber: 1 },
      { title: 'Functions & Scope', description: 'Function declarations, expressions, arrow functions, closures', estimatedTime: 60, orderNumber: 2 },
      { title: 'Arrays & Objects', description: 'Array methods, object manipulation, destructuring', estimatedTime: 60, orderNumber: 3 },
      { title: 'DOM Manipulation', description: 'Selecting elements, event handling, creating/removing elements', estimatedTime: 45, orderNumber: 4 },
      { title: 'Async JavaScript', description: 'Callbacks, Promises, async/await, fetch API', estimatedTime: 60, orderNumber: 5 },
      { title: 'ES6+ Features', description: 'Template literals, spread/rest, modules, classes', estimatedTime: 45, orderNumber: 6 },
      { title: 'Error Handling & Debugging', description: 'Try/catch, debugging tools, error types', estimatedTime: 30, orderNumber: 7 },
    ],
  },
  {
    title: 'React',
    description: 'Build modern user interfaces with React, hooks, state management, and routing.',
    icon: 'Atom',
    orderNumber: 4,
    color: '#61dafb',
    lessons: [
      { title: 'React Introduction', description: 'Components, JSX, and React fundamentals', estimatedTime: 45, orderNumber: 1 },
      { title: 'Props & State', description: 'Passing data with props, managing state with useState', estimatedTime: 60, orderNumber: 2 },
      { title: 'React Hooks', description: 'useEffect, useContext, useRef, useMemo, useCallback', estimatedTime: 60, orderNumber: 3 },
      { title: 'Event Handling & Forms', description: 'Handling events, controlled components, form validation', estimatedTime: 45, orderNumber: 4 },
      { title: 'React Router', description: 'Client-side routing, navigation, route parameters', estimatedTime: 45, orderNumber: 5 },
      { title: 'State Management', description: 'Context API, useReducer, global state patterns', estimatedTime: 60, orderNumber: 6 },
      { title: 'API Integration', description: 'Fetching data, loading states, error handling', estimatedTime: 45, orderNumber: 7 },
      { title: 'Performance Optimization', description: 'React.memo, lazy loading, code splitting', estimatedTime: 45, orderNumber: 8 },
    ],
  },
  {
    title: 'Node.js',
    description: 'Server-side JavaScript with Node.js runtime, modules, and file system.',
    icon: 'Server',
    orderNumber: 5,
    color: '#339933',
    lessons: [
      { title: 'Node.js Introduction', description: 'Runtime environment, npm, package.json', estimatedTime: 30, orderNumber: 1 },
      { title: 'Modules & File System', description: 'CommonJS/ES modules, reading/writing files', estimatedTime: 45, orderNumber: 2 },
      { title: 'HTTP Module', description: 'Creating HTTP servers, handling requests', estimatedTime: 45, orderNumber: 3 },
      { title: 'Streams & Buffers', description: 'Working with streams, buffers, and piping', estimatedTime: 45, orderNumber: 4 },
      { title: 'Environment Variables', description: 'dotenv, configuration management, security', estimatedTime: 30, orderNumber: 5 },
    ],
  },
  {
    title: 'Express.js',
    description: 'Build RESTful APIs with Express.js, middleware, routing, and authentication.',
    icon: 'Route',
    orderNumber: 6,
    color: '#000000',
    lessons: [
      { title: 'Express Basics', description: 'Setting up Express, routing, request/response', estimatedTime: 45, orderNumber: 1 },
      { title: 'Middleware', description: 'Built-in, third-party, and custom middleware', estimatedTime: 45, orderNumber: 2 },
      { title: 'RESTful API Design', description: 'HTTP methods, status codes, REST conventions', estimatedTime: 60, orderNumber: 3 },
      { title: 'Error Handling', description: 'Error middleware, async error handling', estimatedTime: 30, orderNumber: 4 },
      { title: 'Authentication & Security', description: 'JWT, bcrypt, CORS, helmet', estimatedTime: 60, orderNumber: 5 },
      { title: 'File Uploads', description: 'Multer, handling file uploads and storage', estimatedTime: 45, orderNumber: 6 },
    ],
  },
  {
    title: 'MongoDB',
    description: 'NoSQL database with MongoDB, Mongoose ODM, and data modeling.',
    icon: 'Database',
    orderNumber: 7,
    color: '#47a248',
    lessons: [
      { title: 'MongoDB Basics', description: 'Documents, collections, CRUD operations', estimatedTime: 45, orderNumber: 1 },
      { title: 'Mongoose ODM', description: 'Schemas, models, validation, middleware', estimatedTime: 60, orderNumber: 2 },
      { title: 'Queries & Aggregation', description: 'Find, sort, filter, aggregation pipeline', estimatedTime: 60, orderNumber: 3 },
      { title: 'Relationships & Population', description: 'References, embedding, populate method', estimatedTime: 45, orderNumber: 4 },
      { title: 'Indexes & Performance', description: 'Indexing strategies, query optimization', estimatedTime: 45, orderNumber: 5 },
    ],
  },
];

export default courses;
